package cleanup

// Developer caches are classified by recovery contract (see AGENTS.md):
// default-on only for pure download/build caches the owning tool refills
// transparently; opt-in for large caches with a visible rebuild cost; never
// for stores projects consume directly (~\.m2\repository, ~\.nuget\packages,
// pnpm store, Cargo registry\src and git, Pub cache, Deno dir, Playwright
// browsers, model caches, toolchains).

func init() {
	register(
		&Rule{
			ID:              "dev.npm.cache",
			Name:            "npm cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\npm-cache\_cacache`, `{LocalAppData}\npm-cache\_logs`},
			DetectPaths:     []string{`{LocalAppData}\npm-cache`},
			What:            "npm's content-addressed download cache and its debug logs.",
			WhySafe:         "Equivalent to `npm cache clean --force`. Installed node_modules folders are separate and not touched.",
			Impact:          "The next npm install downloads packages again.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.yarn.cache",
			Name:            "Yarn cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\Yarn\Cache`},
			What:            "Yarn (classic) package download cache.",
			WhySafe:         "Equivalent to `yarn cache clean`. Projects' node_modules are not touched.",
			Impact:          "The next yarn install downloads packages again.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.pip.cache",
			Name:            "pip cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\pip\Cache`},
			What:            "pip's HTTP and wheel cache.",
			WhySafe:         "Equivalent to `pip cache purge`. Installed packages and virtual environments are not touched.",
			Impact:          "The next pip install downloads or builds packages again.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.nuget.http-cache",
			Name:            "NuGet HTTP cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\NuGet\v3-cache`, `{LocalAppData}\NuGet\plugins-cache`},
			What:            "NuGet's HTTP response and plugin caches.",
			WhySafe:         "Equivalent to `dotnet nuget locals http-cache --clear`. The global packages folder (~\\.nuget\\packages) is not touched.",
			Impact:          "The next restore queries package feeds again.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.go.build-cache",
			Name:            "Go build cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\go-build`},
			What:            "Compiled package and test results cached by the Go toolchain.",
			WhySafe:         "Equivalent to `go clean -cache`. The module cache and your code are not touched.",
			Impact:          "The next build or test run recompiles from scratch.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.cargo.registry-cache",
			Name:            "Cargo download cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{UserProfile}\.cargo\registry\cache`},
			What:            "Compressed .crate archives downloaded by Cargo.",
			WhySafe:         "Cargo keeps extracted sources separately (registry\\src, untouched) and re-downloads archives when needed.",
			Impact:          "Cargo downloads crates again when a lockfile needs a version that is not extracted.",
			DefaultSelected: true,
		},
		&Rule{
			ID:       "dev.electron.cache",
			Name:     "Electron download cache",
			Category: CategoryDeveloper,
			Roots: []string{
				`{LocalAppData}\electron\Cache`,
				`{LocalAppData}\electron-builder\Cache`,
			},
			What:            "Electron and electron-builder binaries downloaded during installs and builds.",
			WhySafe:         "Pure download caches; the tools download them again when needed.",
			Impact:          "The next Electron install or build downloads binaries again.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.node-gyp.cache",
			Name:            "node-gyp headers",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\node-gyp\Cache`},
			What:            "Node.js headers downloaded by node-gyp to build native modules.",
			WhySafe:         "node-gyp downloads matching headers again on the next native build.",
			Impact:          "The next native module build downloads headers again.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.composer.cache",
			Name:            "Composer cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\Composer\files`, `{LocalAppData}\Composer\repo`, `{LocalAppData}\Composer\vcs`},
			What:            "Composer's package archive, metadata and VCS caches.",
			WhySafe:         "Equivalent to `composer clear-cache`. Global packages and project vendor folders are not touched.",
			Impact:          "The next composer install downloads packages again.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.typescript.cache",
			Name:            "TypeScript typings cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\Microsoft\TypeScript`},
			What:            "Type definitions the TypeScript language service downloads for editor IntelliSense.",
			WhySafe:         "The language service downloads typings again when needed. Project dependencies are not touched.",
			Impact:          "Editor IntelliSense for untyped JavaScript packages is briefly less complete.",
			DefaultSelected: true,
		},
		&Rule{
			ID:              "dev.golangci-lint.cache",
			Name:            "golangci-lint cache",
			Category:        CategoryDeveloper,
			Roots:           []string{`{LocalAppData}\golangci-lint`},
			What:            "Analysis results cached by golangci-lint.",
			WhySafe:         "Equivalent to `golangci-lint cache clean`.",
			Impact:          "The next lint run is slower.",
			DefaultSelected: true,
		},
		&Rule{
			ID:          "dev.gradle.caches",
			Name:        "Gradle caches",
			Category:    CategoryDeveloper,
			Roots:       []string{`{UserProfile}\.gradle\caches`},
			DetectPaths: []string{`{UserProfile}\.gradle`},
			What:        "Gradle's dependency, build-script and transform caches.",
			WhySafe:     "Gradle rebuilds them; files held by running Gradle daemons are skipped. Wrapper distributions and gradle.properties are not touched.",
			Impact:      "The next Gradle build re-downloads dependencies and is much slower.",
		},
	)
}
